config/routes.rb
Rails.application.routes.draw do

  get 'backoffice', to: "backoffice/dashboard#index"

  namespace :backoffice do
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
    end

    resources :ad_details, only: [:show]
    resources :categories, only: [:show]
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members #, controller: {sessions: 'member/sessions'}

  root 'site/home#index'

end

app/controllers/site/ad_details_controller.rb
class Site::AdDetailsController < SiteController
  def show
    @categories = Category.order_by_description
    @ad = Ad.find(params[:id])
  end
end

app/controllers/site/categories_controller.rb
class Site::CategoriesController < SiteController
  def show
    @categories = Category.order_by_description
    @category = Category.friendly.find(params[:id])
    @ads = Ad.by_category(@category.id)
  end
end

app/controllers/site/home_controller.rb
class Site::HomeController < SiteController
  def index
    @categories = Category.order_by_description
    @ads = Ad.descending_order(6, params[:page])
  end
end

app/controllers/site/profile/ads_controller.rb
class Site::Profile::AdsController < Site::ProfileController
  before_action :set_ad, only: [:edit, :update]
  def index
    @ads = Ad.to_the(current_member)
  end

  def edit
    #
  end

  def update
    if @ad.update(params_ad)
      redirect_to site_profile_ads_path, notice: "Anúncio atualizado com sucesso!"
    else
      render :edit
    end
  end

  def new
    @ad = Ad.new
  end

  def create
    @ad = Ad.new(params_ad)
    @ad.member = current_member

    if @ad.save
      redirect_to site_profile_ads_path, notice: "Anúncio criado com sucesso!"
    else
      render :new
    end
  end

  private
    def set_ad
      @ad = Ad.find(params[:id])
    end

    def params_ad
      params.require(:ad).permit(:id, :title, :category_id, :price, :description,
        :description_md, :description_short, :picture, :finish_date)
    end
end

app/controllers/site/profile/dashboard_controller.rb
class Site::Profile::DashboardController < Site::ProfileController

  def index
    #
  end
end

app/controllers/site/profile_controller.rb
class Site::ProfileController < SiteController
  layout "profile"

end

app/controllers/site/search_controller.rb
class Site::SearchController < SiteController
  def ads
    @categories = Category.order_by_description
    @ads = Ad.search(params[:q], params[:page])
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout "site"
  
end

app/helpers/site/ad_details_helper.rb
module Site::AdDetailsHelper
end

app/helpers/site/categories_helper.rb
module Site::CategoriesHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/helpers/site/profile/ads_helper.rb
module Site::Profile::AdsHelper
end

app/helpers/site/profile/dashboard_helper.rb
module Site::Profile::DashboardHelper
end

app/helpers/site/search_helper.rb
module Site::SearchHelper
end

app/views/site/shared/_ads.html.erb
<% @ads.each do |ad| %>
  <div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
      <%= image_tag ad.picture.url(:medium) %>
      <div class="caption">
        <h4 class="pull-right"><%= humanized_money_with_symbol(ad.price) %></h4>
        <h4><%= link_to truncate(ad.title, length: 18), site_ad_detail_path(ad), remote: true, data: { push: :partial } %></h4>
        <p><%= truncate(ad.description_short, length: 100) %></p>
      </div>
      <div class="ratings">
        <p class="pull-right">15 reviews</p>
        <p>
          <span class="glyphicon glyphicon-star"></span>
          <span class="glyphicon glyphicon-star"></span>
          <span class="glyphicon glyphicon-star"></span>
          <span class="glyphicon glyphicon-star"></span>
          <span class="glyphicon glyphicon-star"></span>
        </p>
      </div>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="text-center">
    <%= paginate @ads %>
  </div>
</div>