config/routes.rb
Rails.application.routes.draw do

  get 'backoffice', to: "backoffice/dashboard#index"

  namespace :backoffice do
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
    end

    resources :ad_details, only: [:show]
    resources :categories, only: [:show]
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members #, controller: {sessions: 'member/sessions'}

  root 'site/home#index'

end

app/models/ad.rb
class Ad < ActiveRecord::Base

  #Callbacks
  before_save :md_to_html

  #Associations
  belongs_to :category, counter_cache: true
  belongs_to :member

  #Validates
  validates :title, :picture, :description_md, :description_short, :finish_date, presence:true
  validates :price, numericality: { greater_than: 0 }

  # gem paperclip
  has_attached_file :picture, styles: { large: "800x300", medium: "320x150#", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  #gem money-rails
  monetize :price_cents

  #SCOPES
  scope :descending_order, -> (quantity = 10, page = 1) {
    limit(quantity).order(created_at: :asc).page(page).per(6)
  }

  scope :search, -> (term, page = 1) {
    where( "lower(title) LIKE ?", "%#{term.downcase}%" ).page(page).per(6)
  }

  scope :to_the, -> (member) { where(member_id: member.id) }
  scope :by_category, -> (id) { where(category: id) }

  private
  def md_to_html
    options = {
      filter_html: true,
      link_attributes: {
        rel: "nofollow",
        target: "_blank"
      }
    }

    extensions = {
      space_after_headers: true,
      autolink: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    self.description = markdown.render(self.description_md)

  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # CONSTANTS
  ROLES = {:full_access => 0, :restrict_access => 1}

  # ENUMS
  enum role: ROLES
  # enum role: {:full_access => 0, :restrict_access => 1}

  #SCOPES
  scope :with_full_access, -> { where(role: ROLES[:full_access]) }
  scope :with_restrict_access, -> { where(role: ROLES[:restrict_access]) }

  # scope :with_full_access, -> { where(role: Admin.roles[:full_access]) }
  # scope :with_restrict_access, -> { where(role: Admin.roles[:full_access]) }


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  #Gem FriendlyId
  include FriendlyId
  friendly_id :description, use: :slugged

  #Associations
  has_many :ads

  # Validations
  validates_presence_of :description

  #SCOPES
  scope :order_by_description, -> { order(:description) }

end

app/models/member.rb
class Member < ActiveRecord::Base
  has_many :ads
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Modulo Pundit
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Set Layout
  layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller? && resource_name == :admin
      "backoffice_devise"
    elsif devise_controller? && resource_name == :member
      "site_devise"
    else
      "application"
    end
  end

  def user_not_authorized
    flash[:alert] = I18n.t('messages.not_authorized')
    redirect_to(request.referrer || root_path)
  end

  def after_sign_in_path_for(resource)
    if devise_controller? && resource_name == :member
     site_profile_dashboard_index_path
   end
  end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :authenticate_admin!

  layout "backoffice"

  def pundit_user
    current_admin # current_user for Pundit
  end
end

app/controllers/site/ad_details_controller.rb
class Site::AdDetailsController < SiteController
  def show
    @categories = Category.order_by_description
    @ad = Ad.find(params[:id])
  end
end

app/controllers/site/home_controller.rb
class Site::HomeController < SiteController
  def index
    @categories = Category.order_by_description
    @ads = Ad.descending_order(6, params[:page])
  end
end

app/controllers/site/profile_controller.rb
class Site::ProfileController < SiteController
  layout "profile"

end

app/controllers/site/search_controller.rb
class Site::SearchController < SiteController
  def ads
    @categories = Category.order_by_description
    @ads = Ad.search(params[:q], params[:page])
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout "site"
  
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
  OptionForRoles = Struct.new(:id, :description)

  def options_for_role
    Admin.roles_i18n.map do |key, value|
      OptionForRoles.new(key, value)
    end
  end

end

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/backoffice/send_mail_helper.rb
module Backoffice::SendMailHelper
end

app/helpers/site/ad_details_helper.rb
module Site::AdDetailsHelper
end

app/helpers/site/categories_helper.rb
module Site::CategoriesHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/helpers/site/search_helper.rb
module Site::SearchHelper
end

app/views/backoffice/admins/shared/_form.html.erb
<h1 class="page-header"><%= action_message %></h1>
<% if @admin.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="panel panel-default">
  <div class="panel-heading">
    <%= action_message %>
  </div>
  <div class="panel-body">
    <div class="col-lg-6">
      <%= form_for([:backoffice, @admin]) do |f|  %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class:"form-control", placeholder:"#{t('labels.name_of_administrator')}" %>
        </div>
        <% if policy(@admin).edit? %>
          <div class="form-group">
            <%= f.label :role %>
            <%= f.collection_radio_buttons :role, options_for_role, :id, :description do |b| %>
              <div class="radio">
                <%= b.label { b.radio_button + b.text } %>
              </div>
            <% end %>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class:"form-control", placeholder:"#{t('labels.email_of_administrator')}" %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class:"form-control", placeholder:"#{t('labels.password')}" %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class:"form-control", placeholder:"#{t('labels.password_confirmation')}" %>
        </div>
        <button type="submit" class="btn btn-default"><%= t('buttons.save') %></button>
      <% end %>
    </div>
  </div>
</div>

app/views/backoffice/admins/shared/_send_mail_modal.html.erb
<div class="modal fade" id="sendMailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel"><%= t('labels.new_message') %></h4>
      </div>
      <%= form_tag(backoffice_send_mail_index_path, remote: true) do %>
        <div class="modal-body">
            <div class="form-group">
              <%= label_tag :"recipient-name", t('labels.recipient'), class:"control-label" %>
              <%= text_field_tag :"recipient-name", nil, class:"form-control", readonly:"readonly" %>
            </div>
            <div class="form-group">
              <%= label_tag :"recipient-name", t('labels.subject'), class:"control-label" %>
              <%= text_field_tag :"subject-text", nil, class:"form-control", required:"required" %>
            </div>
            <div class="form-group">
              <%= label_tag :"message-text", t('labels.message'), class:"control-label" %>
              <%= text_area_tag :"message-text", nil, class:"form-control", required:"required" %>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('buttons.close') %></button>
          <%= submit_tag t('buttons.send_message'), class:"btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/shared/_notifications.html.erb
<% if notice %>
  <%= javascript_tag do %>
    $.notify({
      message: "<%= notice %>",
      icon: "glyphicon glyphicon-ok" }, {
        type: "success",
        placement: {
		      from: "top",
		      align: "center"
        }
      });
  <% end %>
<% end %>

<% if alert %>
  <%= javascript_tag do %>
    $.notify({
      message: "<%= alert %>",
      icon: "glyphicon glyphicon-remove" }, {
        type: "danger",
        placement: {
		      from: "top",
		      align: "center"
        }
      });
  <% end %>
<% end %>